name: agriconnectapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0
  cloud_firestore: 6.0.2
  firebase_storage: ^13.0.2
  google_sign_in: ^6.2.0
  google_fonts: ^6.2.1
  font_awesome_flutter: ^10.7.0
  ionicons: ^0.2.2
  email_validator: ^2.1.17
  flutter_spinkit: ^5.1.0
  image_picker: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/address/region.json
  - assets/address/province.json
  - assets/address/city.json
  - assets/address/barangay.json
