// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEkCmJb4azAr61HCZ_25Vl0th2r39YZ6s',
    appId: '1:57309570211:web:5236e472c66ca4fedd0b16',
    messagingSenderId: '57309570211',
    projectId: 'agriconnect-c014c',
    authDomain: 'agriconnect-c014c.firebaseapp.com',
    storageBucket: 'agriconnect-c014c.firebasestorage.app',
    measurementId: 'G-HBV88658JT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANECWHfjHSrCBr0sxRt_0AMYvgvoX6kZQ',
    appId: '1:57309570211:android:3253a0809986d2a0dd0b16',
    messagingSenderId: '57309570211',
    projectId: 'agriconnect-c014c',
    storageBucket: 'agriconnect-c014c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjipaOO8QB6QPEt4DpVWS06mALnBGp-pg',
    appId: '1:57309570211:ios:04094050d7a49494dd0b16',
    messagingSenderId: '57309570211',
    projectId: 'agriconnect-c014c',
    storageBucket: 'agriconnect-c014c.firebasestorage.app',
    androidClientId: '57309570211-01qfe8p3i8m1kd057u7n0mt78rr4nb5r.apps.googleusercontent.com',
    iosClientId: '57309570211-crbb5krqj84i4qijuvbjq8cc7ohf9g1q.apps.googleusercontent.com',
    iosBundleId: 'com.example.agriconnectapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjipaOO8QB6QPEt4DpVWS06mALnBGp-pg',
    appId: '1:57309570211:ios:04094050d7a49494dd0b16',
    messagingSenderId: '57309570211',
    projectId: 'agriconnect-c014c',
    storageBucket: 'agriconnect-c014c.firebasestorage.app',
    androidClientId: '57309570211-01qfe8p3i8m1kd057u7n0mt78rr4nb5r.apps.googleusercontent.com',
    iosClientId: '57309570211-crbb5krqj84i4qijuvbjq8cc7ohf9g1q.apps.googleusercontent.com',
    iosBundleId: 'com.example.agriconnectapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEkCmJb4azAr61HCZ_25Vl0th2r39YZ6s',
    appId: '1:57309570211:web:47f6f3cf01b0b2cedd0b16',
    messagingSenderId: '57309570211',
    projectId: 'agriconnect-c014c',
    authDomain: 'agriconnect-c014c.firebaseapp.com',
    storageBucket: 'agriconnect-c014c.firebasestorage.app',
    measurementId: 'G-CT2VE6FZ29',
  );
}
